# Generated by Django 2.2.16 on 2022-04-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comments',
            new_name='comment',
        ),
    ]
