# Generated by Django 2.2.16 on 2022-04-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220411_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.Title', verbose_name='Название'),
        ),
    ]
